# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

require 'capistrano/rbenv'
# require 'capistrano/chruby'

require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'whenever/capistrano'
require 'capistrano/sidekiq'
require 'capistrano/sidekiq/monit'


# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
capistrano_tasks_dir = File.expand_path './lib/capistrano/tasks'
Dir.glob("#{capistrano_tasks_dir}/*.cap").each do |recipie|
  import recipie
end
