# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'aws-sdk-s3', require: false
gem 'activerecord-import'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'chewy', git: 'https://github.com/noellabo/chewy', branch: 'es6-client-compatibility-workaround-for-es7'
gem 'spree_datashift_prod_import', path: 'vendor/gems/spree_datashift_prod_import'
gem 'datashift', path: 'vendor/gems/datashift'
gem 'datashift_spree', path: 'vendor/gems/datashift_spree'
gem 'sidekiq'
gem 'spree', path: 'vendor/gems/spree'
gem 'spree_auth_devise'
gem 'spree_gateway', '~> 3.4'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', ref: 'be7a9a9fa866054a81270f15e8e5fb289e80a9d7'
gem 'spree_multi_vendor', path: 'vendor/gems/spree_multi_vendor'
gem 'suite_rest', git: 'https://github.com/pinak1180/suite_rest.git'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'letter_opener'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :deployment do
  gem 'capistrano', '~> 3.11'
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rails', '~> 1.3.1', require: false
  gem 'capistrano-rbenv', '~> 2.1.3', require: false
  gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq', require: false
  gem 'whenever', require: false
end
